# Generated by Django 4.1.7 on 2023-03-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_buscapreco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='data_contacao',
            new_name='data_cotacao',
        ),
    ]
